-- Problematicas
insert into problematicas(nombre_problematica)
values
('Ceguera'),
('Sordera profunda'),
('Discapacidad auditiva (hipoacusia)'),
('Discapacidad motriz severa (daño neurológico)'),
('Discapacidad motriz moderada (limitación de alguna parte específica del cuerpo)'),
('Autoestima'),
('Manejo de emociones'),
('Situaciones personales fuera de lo académico'),
('Seguimiento a la atención brindada antes de la contingencia por COVID-19'),
('Falta de socialización'),
('Acompañamiento en duelo'),
('Habilidades para la vida'),
('Problemáticas familiares'),
('Habilidades para la vida'),
('Inclusión comunidad LGBTQ+'),
('Bienestar y equilibrio'),
('Calidad de vida'),
('Comunicación asertiva'),
('Control de impulsos'),
('Problemas de pareja'),
('Dificultad en las relaciones personales'),
('Asperger'),
('Manejo de conflictos'),
('Reporte de acoso'),
('Seguridad física'),
('Transgenero'),
('Violencia familiar'),
('Bullying cibernético'),
('Bullying'),
('Violencia de género'),
('Muerte de familiar por COVID'),
('Platica motivacional'),
('Adaptación a la universidad'),
('Sexualidad'),
('Relaciones afectivas'),
('Toma de decisiones'),
('Violacion/Abuso sexual'),
('Trastorno del sueño'),
('Esquizofrenia'),
('Psicosocial o mental'),
('Trastorno Límite de la Personalidad (TLP)'),
('Trastorno Obsesivo Compulsivo'),
('Brote psicotico'),
('Ideación suicida'),
('Epilepsia'),
('Ansiedad'),
('Depresión'),
('Canalización'),
('Paciente psiquiátrico'),
('Técnicas y hábitos de estudio'),
('Asesoría Académica'),
('Necesidades de equipo de computo'),
('Becas'),
('Bajas temporales'),
('bajas definitivas y bajas extemporáneas'),
('Hábitos y técnicas de estudio'),
('Problemas de administración del tiempo'),
('Inconformidad o dificultad con algún docente'),
('Conflicto entre estudiantes y docentes'),
('Rezago educativo'),
('Apoyo en trámites'),
('Tutorías'),
('Conferencia en línea'),
('Rendimiento académico'),
('Indice de reprobacion'),
('Falta de computadora e internet'),
('Ausentismo y reprobación por inadaptación al cambio'),
('con relación al modelo de enseñanza y aprendizaje'),
('Disgusto por clases en modalidad en línea'),
('Dislexia'),
('Dislalia'),
('Trastorno por déficit de atención (TDA)'),
('Hiperactividad'),
('Dificultad con asignaturas'),
('COVID-19'),
('Problemas de salud'),
('Embarazo'),
('Adicciones y Educación sexual')
-- Unidades Academicas
insert into unidad_academica(nombre_unidad)
values
('Facultad de Ciencias Químicas e Ingeniería'),
('Facultad de Artes'),
('Facultad de Contaduría y Administración'),
('Facultad de Deportes'),
('Facultad de Derecho'),
('Facultad de Economía y Relaciones Internacionales'),
('Facultad de Idiomas'),
('Facultad de Medicina y Psicología'),
('Facultad de Odontología'),
('Facultad de Turismo y Mercadotecnia'),
('Instituto de Investigaciones Históricas')
-- Carreras
